name: return_success_or_error
description: Usecase abstraction returning success or errorr from a call made by the data source
version: 0.1.2
homepage: https://github.com/pwlimaverde/return_success_or_error

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: 0.0.1-dev.12
  flutter_test:
    sdk: flutter

flutter: