name: return_success_or_error
description: Usecase abstraction returning success or errorr from a call made by the data source
version: 0.16.0
homepage: https://github.com/pwlimaverde/return_success_or_error

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=3.16.7"

dependencies:
  flutter:
    sdk: flutter
  
  

dev_dependencies:
  mocktail: ^1.0.2
  flutter_test:
    sdk: flutter

flutter: