name: return_success_or_error
description: Usecase abstraction returning success or errorr from a call made by the data source
version: 0.4.1
homepage: https://github.com/pwlimaverde/return_success_or_error

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter

flutter: