name: example_app_flutter_get
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  return_success_or_error:
    path: ../../
  connectivity_plus: ^6.1.4

  cupertino_icons: ^1.0.8
  get: ^5.0.0-release-candidate-9.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
